### PR TITLE
add first part of pandas notebook

### PR DESCRIPTION
**Pull request by wikfeldt**
starting with an appetizer

### CODE REVIEW

**Comment by wikfeldt** [comment]
not sure why github actions fails for this PR, logs unclear to me. Could it be because it's a draft PR?

**Comment by rkdarst** [comment]
Looks like a race condition in pushing to the gh-pages branch.  All the actual builds succeeded, so I guess it can be considered successful for merging purposes.

**Comment by annefou** [comment]
Yes I think we should merge it.

**Comment by bast** [comment]
Merging. I think this will help other sections to align/refer better to other episodes.

**Pull request merged**
