### PR TITLE
thebe

### PR DESCRIPTION
**Pull request by rkdarst**
- content/pandas: Basic revision, no major changes.
- Thebe: demonstrate Thebe to run code inline

### CODE REVIEW

**Comment by rkdarst** [comment]
You can preview this here: https://aaltoscicomp.github.io/python-for-scicomp/branch/thebe/pandas/

**Comment by bast** [comment]
Seems to work well.

**Comment by bast** [comment]
Is this ready to go?

**Comment by rkdarst** [comment]
I guess no reason not to?  Can be used as an example and tested until next time...

**Pull request merged**
