### PR TITLE
mpi4py example

### PR DESCRIPTION
**Pull request by bast**
to be turned into a demo and text to be added

### CODE REVIEW

**Review by annefou — APPROVED** [review]
Nice example! 

What do we do for dependencies? 

mpi4py is not available on Windows. And anyway `mpi4py` is not very useful on a laptop... 
Should we add a link to binder to test it?

**Comment by bast** [comment]
Binder is a great idea! It needs `mpi4py` and an MPI installation (I use OpenMPI). And I use it on a laptop :-)

**Comment by bast** [comment]
If we run it on mybinder, do the runners have two cores? Because if it only has one core, the example will still work but it will take more time "in parallel" than sequentially.

**Comment by annefou** [comment]
no 1 core only. On EOSC or other similar services (for instance Galaxy EU) I think we can get a lot more (about 8 cores) but it is over complicated (registration ,etc.) for such course.  
I think it is enough to show a demo. Those who will be using it are targeting multi-core platforms so they can try it out.

**Pull request merged**
