### PR TITLE
is this better?

### PR DESCRIPTION
**Pull request by bast**
i often use the former version but i think the -m venv
is "better"/recommended?

### CODE REVIEW

**Comment by rkdarst** [comment]
Good question... my quick search seems to also show we should recommend venv.  Once I checked the difference in layouts and they were pretty similar, main difference was how it did symlinks.

So I am pro this PR but would be interested in others that my know better...

**Comment by bast** [comment]
We can leave the PR open since also the other way should work.

**Review by annefou — COMMENTED** [review]
I dn't think it works on Windows.

**Comment by bast** [comment]
> I dn't think it works on Windows.

Thanks! In this case let's not merge. Ideally even close.

**Comment by annefou** [comment]
I just tested it and it seems to work fine.

**Comment by bast** [comment]
It should work since Python 3. This did not exist in Python 2 AFAIK.

**Comment by annefou** [comment]
By the way there is a typo when installing libraries with pip. we need 2 == when specifying the version (I probably made this mistake...).

**Comment by annefou** [comment]
Did we ask learners to install `virtualenv`? Should we add a note in the episode?

**Comment by bast** [comment]
The good thing about the `-m venv` route is that then an installation should not be needed.

**Comment by bast** [comment]
> By the way there is a typo when installing libraries with pip. we need 2 == when specifying the version (I probably made this mistake...).

I will add this typo fix to my upcoming PR.

**Comment by annefou** [comment]
> The good thing about the `-m venv` route is that then an installation should not be needed.

Awesome! I did not know about it! Then it is much better!

Testing installation of numpy 1.13.1 on windows with virtualenv does not seem to work (it does not seem to be available e.g. wants to compile it (so one needs to have a compiler available).

matplotlib works perfectly.

**Comment by bast** [comment]
Good point, let's avoid `numpy`, we want to avoid any compilation. Thanks for testing it. I will now send my PR although a bit of more work remains so that you see that I hopefully did not miss anything.

**Pull request merged**
