### PR TITLE
jupyter: Add jupyter exercises

### PR DESCRIPTION
**Pull request by rkdarst**
- This is a first draft of Jupyter exercises: the minimum I think we
  need in order to get through the course.
- First draft only, I haven't given these too much thought overall.
- To review:
  - Do they generally make sense?
  - I would like to add a few conceptual exercises.
  - I worry this is too long, we have currently planned 30 minutes for
    Jupyter.  Since this is the very start, it's going to be slow
    going getting started...
  - Do we instead want to start with one of the CodeRefinery examples
    to make it concrete.  Hm, yes, we should probably do that...

### CODE REVIEW

**Comment by rkdarst** [comment]
How about we record the "darts problem" as a prerequisite of the course... or something to watch during the course?

**Comment by bast** [comment]
I think it's a good start. Later we can align the exercises better to prepare for what comes later.

Darts problem: I think it's a good example. As to recording I don't really have time to pack more into this week and am happy if I can find some time for material development.

**Comment by annefou** [comment]
Maybe we can link to the JupyterLab video demo (to watch before the course); the one shown at https://jupyterlab.readthedocs.io/en/stable/getting_started/overview.html

And please could you take related issues (or at least mention on which episode you are working). I feel like working on the same topic is not very efficient.

**Comment by bast** [comment]
Merging to have a starting point. Let's iterate from here.

**Pull request merged**
