### PR TITLE
installation: Add installation instructions in a new page

### PR DESCRIPTION
**Pull request by rkdarst**
- Copied from existing instructions, but heavily revised.
- Recommend only anaconda as the tool of choice.
- Also point to some other tools, such as text editor, git, etc.
  These are not as important so perhaps they could be de-empahasized,
  but if learners don't have these then they will get stuck with some
  parts.  I haven't thought too much to make sure I considered all the
  cases here... revisions welcome.
- For the most part, link to CodeRefinery installation instructions
  (which mostly apply here).
- Review:
  - Is the content good?  Is it mostly correct and what we want?
  - I am sure there is still room for minor fixups, this is just a
    first pass.

### CODE REVIEW

**Comment by rkdarst** [comment]
Oh, also the page needs to be linked from index.  For that, the other revisions need to be merged first, then added in two places: toctree (extras), and under prereqs (the place is marked).

**Comment by bast** [comment]
Other PRs merged. Would you like me to add the two links?

**Review by bast — APPROVED** [review]

**Comment by bast** [comment]
One thing I need to test and myself get better at is how venv can coexist inside conda since I will need it in one episode.

**Comment by rkdarst** [comment]
Hm... from my understanding, a venv can't exist in a conda-managed python installation.  This is a really important point for installation!  What should we do?

Merging to be able to link to the page, thanks for the review.

**Pull request merged**
